#!/usr/bin/env python3
"""
Tier 1 data integrity backfill (2026-04-28): tag historical trades whose
recorded fields are infrastructure artifacts rather than real strategy
outcomes, and retroactively correct exit_reason labels that were
generated by pre-fix code paths.

This script does THREE things, all idempotent:

1. **CATASTROPHIC_SHORT** — Flag the 4 SHORT trades from Apr 13-14 whose
   `exit_price=99` looks like a settlement-time artifact, not a real
   sell at 99 cents. We have no wallet_pnl to verify. They account for
   $22.73 of the headline live "loss" but should not be treated as
   strategy-quality signals.

   Targets (4 rows):
     - id=424 KXBTC-26APR1315-B72150 short 12 @ 11c -> 99c, pnl -10.71
     - id=428 KXBTC-26APR1316-B72450 short 7  @ 18c -> 99c, pnl -5.70
     - id=439 KXBTC-26APR1318-B73150 short 16 @ 6c  -> 99c, pnl -5.13
     - id=460 KXBTC-26APR1401-B74450 short 2  @ 17c -> 99c, pnl -1.19

2. **PRE_BUG027_WALLET** — Flag the 4 trades whose `wallet_pnl` was
   captured under the buggy post-entry snapshot timing (before commit
   0ce407e on 2026-04-23). Their `pnl` values are correct (already
   backfilled by scripts/backfill_pnl_bug027.py) but the persisted
   `wallet_pnl` is stale and reconstructs as `pnl + entry_cost +
   entry_fees`. We don't recompute wallet_pnl (not recoverable from
   row data alone) -- the flag tells dashboards / alerting to ignore
   the drift on these specific rows.

   Targets (4 rows): id IN (702, 716, 750, 788).

3. **EXIT_REASON_RECLASSED** — Retroactively correct exit_reason on
   historical rows where the recorded label is wrong relative to the
   realized pnl outcome:
     * exit_reason = 'TAKE_PROFIT' AND pnl < -$0.05  ->  'STOP_LOSS'
     * exit_reason = 'STOP_LOSS'   AND pnl > +$0.05  ->  'TAKE_PROFIT'
   The original label is preserved by writing `data_quality_flag =
   'EXIT_REASON_RECLASSED'` so analysts can find these rows. The
   $0.05 threshold avoids reclassifying near-scratch trades where
   the original intent label is meaningful.

   Pre-flight scan on prod found 5 rows that match (4 mislabeled
   TAKE_PROFITs, 0 mislabeled STOP_LOSSes). These are all from the
   pre-Apr-23 era when the order_response code path had sign issues
   on shorts AND an intent-vs-outcome race on rapid price moves.
   Current code (post-BUG-027) labels exit_reason correctly on all
   3 trades since then.

Defaults to ``--dry-run`` and prints what would change. Use ``--apply``
to commit. Always back up the DB before ``--apply``.

Usage:
    # Local dev DB, dry run first:
    DATABASE_URL=postgresql://kalshi:kalshi_secret@localhost:5433/kbtc \\
        python3 scripts/backfill_data_quality_flags.py

    # Local dev DB, apply changes:
    DATABASE_URL=... python3 scripts/backfill_data_quality_flags.py --apply

    # Remote (run inside the bot container so it sees DATABASE_URL):
    ssh "$KBTC_DEPLOY_HOST" \\
        "docker exec kbtc-bot python3 /app/scripts/backfill_data_quality_flags.py --apply"

    # Run only one of the three tasks:
    python3 scripts/backfill_data_quality_flags.py --apply --only catastrophic_short
    python3 scripts/backfill_data_quality_flags.py --apply --only pre_bug027_wallet
    python3 scripts/backfill_data_quality_flags.py --apply --only exit_reason_reclass

Migration prerequisite:
    backend/migrations/007_data_quality_flag.sql must have been applied.
    The script aborts with an instructive error if the column is missing.
"""
from __future__ import annotations

import argparse
import os
import sys
from typing import List, Optional, Tuple

import psycopg


CATASTROPHIC_SHORT_IDS = (424, 428, 439, 460)
PRE_BUG027_WALLET_IDS = (702, 716, 750, 788)

EXIT_RECLASS_PNL_THRESHOLD = 0.05


def _resolve_db_url(explicit: Optional[str]) -> str:
    if explicit:
        return explicit
    url = os.environ.get("DATABASE_URL")
    if not url:
        raise SystemExit(
            "DATABASE_URL not set. Pass --db-url or export DATABASE_URL."
        )
    return url


def _check_migration(cur) -> None:
    """Abort if migration 007 hasn't been applied."""
    cur.execute(
        """
        SELECT column_name FROM information_schema.columns
        WHERE table_name = 'trades' AND column_name = 'data_quality_flag'
        """
    )
    if cur.fetchone() is None:
        raise SystemExit(
            "trades.data_quality_flag column missing. Apply migration "
            "backend/migrations/007_data_quality_flag.sql first:\n"
            "  ssh \"$KBTC_DEPLOY_HOST\" "
            "\"docker exec -i kbtc-db psql -U kalshi -d kbtc\" "
            "< backend/migrations/007_data_quality_flag.sql"
        )


def _flag_catastrophic_shorts(cur, *, apply: bool) -> int:
    """Tag the 4 Apr 13-14 short trades. Returns rows that would change."""
    cur.execute(
        """
        SELECT id, ticker, direction, contracts, entry_price, exit_price,
               pnl, exit_reason, data_quality_flag
        FROM trades
        WHERE id = ANY(%s)
        ORDER BY id
        """,
        (list(CATASTROPHIC_SHORT_IDS),),
    )
    rows = cur.fetchall()

    print("\n── Task 1: CATASTROPHIC_SHORT ──────────────────────────────")
    if not rows:
        print("  No matching trades found. (Trade IDs may have changed.)")
        return 0

    n_changed = 0
    for r in rows:
        rid, tkr, dir_, cnt, ep, xp, pnl, reason, flag = r
        if flag == "CATASTROPHIC_SHORT":
            print(f"  [skip] id={rid}  already flagged")
            continue
        if dir_ != "short":
            print(f"  [skip] id={rid}  direction={dir_!r} (expected 'short') -- skipping defensively")
            continue
        if abs(float(xp) - 99.0) > 0.01:
            print(f"  [skip] id={rid}  exit_price={xp} (expected ~99) -- skipping defensively")
            continue
        action = "would tag" if not apply else "TAGGED"
        print(
            f"  [{action}] id={rid}  {tkr}  short {cnt} @ {ep} -> {xp}  "
            f"pnl={pnl}  reason={reason}"
        )
        if apply:
            cur.execute(
                "UPDATE trades SET data_quality_flag = 'CATASTROPHIC_SHORT' WHERE id = %s",
                (rid,),
            )
        n_changed += 1
    print(f"  Total: {n_changed} row(s) {'changed' if apply else 'would change'}")
    return n_changed


def _flag_pre_bug027_wallet(cur, *, apply: bool) -> int:
    """Tag the 4 trades with stale wallet_pnl from pre-fix snapshot timing."""
    cur.execute(
        """
        SELECT id, ticker, direction, contracts, pnl, wallet_pnl, pnl_drift,
               entry_cost_dollars, fees, fill_source, data_quality_flag
        FROM trades
        WHERE id = ANY(%s)
        ORDER BY id
        """,
        (list(PRE_BUG027_WALLET_IDS),),
    )
    rows = cur.fetchall()

    print("\n── Task 2: PRE_BUG027_WALLET ───────────────────────────────")
    if not rows:
        print("  No matching trades found.")
        return 0

    n_changed = 0
    for r in rows:
        rid, tkr, dir_, cnt, pnl, wp, drift, ec, fees, fs, flag = r
        if flag == "PRE_BUG027_WALLET":
            print(f"  [skip] id={rid}  already flagged")
            continue
        # Sanity: verify the row matches the artifact pattern
        # wallet_pnl ≈ pnl + entry_cost + ~entry_fees
        if pnl is None or wp is None or ec is None:
            print(f"  [skip] id={rid}  missing pnl/wallet_pnl/entry_cost -- not the expected artifact")
            continue
        # Half the fees are entry-side, roughly. Be lenient: within $0.05.
        predicted = float(pnl) + float(ec) + float(fees) * 0.5
        observed = float(wp)
        if abs(predicted - observed) > 0.05:
            print(
                f"  [skip] id={rid}  artifact-prediction mismatch  "
                f"predicted={predicted:.4f} observed={observed:.4f}  "
                f"(this row may not be a pre-BUG027 wallet artifact)"
            )
            continue
        action = "would tag" if not apply else "TAGGED"
        print(
            f"  [{action}] id={rid}  {tkr}  pnl={pnl} wallet_pnl={wp} drift={drift}  "
            f"entry_cost={ec} fees={fees}  -- artifact confirmed"
        )
        if apply:
            cur.execute(
                "UPDATE trades SET data_quality_flag = 'PRE_BUG027_WALLET' WHERE id = %s",
                (rid,),
            )
        n_changed += 1
    print(f"  Total: {n_changed} row(s) {'changed' if apply else 'would change'}")
    return n_changed


def _price_pnl_sign_consistent(direction: str, ep: float, xp: float, pnl: float) -> bool:
    """Sanity check: does the direction-aware price move agree with pnl sign?

    For a long that exited above entry, pnl should not be strongly negative.
    For a short that exited below entry, pnl should not be strongly negative.
    Strong disagreement (>$0.20 in the wrong direction) means the row's pnl
    was computed by a broken formula and we shouldn't trust it for
    reclassification either. Returns True if the sign relationship is at
    least directionally consistent (within a small tolerance for fees).
    """
    expected_sign_pos = (
        (direction == "long" and xp > ep)
        or (direction == "short" and xp < ep)
    )
    if expected_sign_pos and pnl < -0.20:
        return False
    if not expected_sign_pos and pnl > 0.20:
        return False
    return True


def _reclass_exit_reason(cur, *, apply: bool) -> int:
    """Reclassify mislabeled TAKE_PROFIT / STOP_LOSS rows based on realized pnl.

    Skips rows where the recorded pnl and the entry/exit price direction
    disagree (rare pre-fix accounting bugs that corrupted both fields). Such
    rows get the ``CORRUPTED_PNL`` flag instead so analysts can find and
    investigate them without auto-reclassifying based on suspect data.
    """
    cur.execute(
        """
        SELECT id, ticker, direction, contracts, entry_price, exit_price,
               pnl, exit_reason, data_quality_flag
        FROM trades
        WHERE trading_mode = 'live'
          AND (
              (exit_reason = 'TAKE_PROFIT' AND pnl < -%s)
              OR (exit_reason = 'STOP_LOSS' AND pnl > %s)
          )
        ORDER BY id
        """,
        (EXIT_RECLASS_PNL_THRESHOLD, EXIT_RECLASS_PNL_THRESHOLD),
    )
    rows = cur.fetchall()

    print("\n── Task 3: EXIT_REASON_RECLASSED ───────────────────────────")
    if not rows:
        print("  No mislabeled rows found. Either backfill already ran or no bad data.")
        return 0

    n_changed = 0
    n_corrupted = 0
    for r in rows:
        rid, tkr, dir_, cnt, ep, xp, pnl, reason, flag = r
        if flag in ("EXIT_REASON_RECLASSED", "CORRUPTED_PNL"):
            print(f"  [skip] id={rid}  already flagged ({flag})")
            continue
        if not _price_pnl_sign_consistent(dir_, float(ep), float(xp), float(pnl)):
            action = "would tag CORRUPTED_PNL" if not apply else "TAGGED CORRUPTED_PNL"
            print(
                f"  [{action}] id={rid}  {tkr}  {dir_} {cnt} @ {ep} -> {xp}  "
                f"pnl={pnl} reason={reason}  -- price-vs-pnl direction inconsistent, "
                f"skipping reclass"
            )
            if apply:
                cur.execute(
                    "UPDATE trades SET data_quality_flag = 'CORRUPTED_PNL' WHERE id = %s",
                    (rid,),
                )
            n_corrupted += 1
            continue
        if reason == "TAKE_PROFIT" and float(pnl) < -EXIT_RECLASS_PNL_THRESHOLD:
            new_reason = "STOP_LOSS"
        elif reason == "STOP_LOSS" and float(pnl) > EXIT_RECLASS_PNL_THRESHOLD:
            new_reason = "TAKE_PROFIT"
        else:
            print(f"  [skip] id={rid}  doesn't match reclass criteria -- skipping defensively")
            continue
        action = "would change" if not apply else "CHANGED"
        print(
            f"  [{action}] id={rid}  {tkr}  {dir_} {cnt} @ {ep} -> {xp}  "
            f"pnl={pnl}  '{reason}' -> '{new_reason}'"
        )
        if apply:
            cur.execute(
                """UPDATE trades
                   SET exit_reason = %s, data_quality_flag = 'EXIT_REASON_RECLASSED'
                   WHERE id = %s""",
                (new_reason, rid),
            )
        n_changed += 1
    print(
        f"  Total: {n_changed} reclassed, {n_corrupted} tagged CORRUPTED_PNL "
        f"({'changed' if apply else 'would change'})"
    )
    return n_changed + n_corrupted


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Backfill data_quality_flag and corrected exit_reason on historical live trades.",
    )
    parser.add_argument("--db-url", type=str, default=None,
                        help="PostgreSQL URL (default: DATABASE_URL env)")
    parser.add_argument("--apply", action="store_true",
                        help="Actually write changes (default: dry run only).")
    parser.add_argument("--only", type=str, default=None,
                        choices=("catastrophic_short", "pre_bug027_wallet", "exit_reason_reclass"),
                        help="Run only one of the three tasks (default: all three).")
    args = parser.parse_args()

    db_url = _resolve_db_url(args.db_url)
    mode_label = "APPLY" if args.apply else "DRY-RUN"
    only_label = f" only={args.only}" if args.only else ""
    print(f"=== backfill_data_quality_flags.py [{mode_label}{only_label}] ===")

    total = 0
    with psycopg.connect(db_url) as conn:
        with conn.cursor() as cur:
            _check_migration(cur)
            # Task ordering matters: when a row qualifies for multiple
            # flags, we want the *most descriptive* flag to win (last
            # write wins on data_quality_flag). Run reclass FIRST (so
            # the exit_reason gets corrected), then the structural
            # quarantine flags so they take precedence on the same row.
            # Example: trade 428 is both a CATASTROPHIC_SHORT and an
            # EXIT_REASON_RECLASSED. The CATASTROPHIC quarantine is the
            # stronger statement (the whole row is suspect), so it must
            # be the final tag.
            if args.only in (None, "exit_reason_reclass"):
                total += _reclass_exit_reason(cur, apply=args.apply)
            if args.only in (None, "pre_bug027_wallet"):
                total += _flag_pre_bug027_wallet(cur, apply=args.apply)
            if args.only in (None, "catastrophic_short"):
                total += _flag_catastrophic_shorts(cur, apply=args.apply)
            if args.apply:
                conn.commit()
                print(f"\nCommitted. Total rows changed: {total}")
            else:
                conn.rollback()
                print(f"\nDry run. Total rows that would change: {total}")
                print("Re-run with --apply to commit.")

    print("\nReminder: re-run scripts/backfill_attribution.py after --apply so")
    print("daily_attribution reflects the corrected exit_reason breakdown.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
